### ISSUE TITLE
non-issue

### ISSUE THREAD

**Issue by BachoSeven** [aloussase/manjar-dots#1]
I think you would like `stig`, if you ever use bittorents; it's written in python and it's the best TUI torrent client I have used so far. Still in development but fully usable.

https://github.com/rndusr/stig

P.S. If you look through the issues over there, I also wrote a little theme for it

P.P.S. It's in the `AUR`: [stig](https://aur.archlinux.org/packages/stig/) [stig-git](https://aur.archlinux.org/packages/stig-git/)

**Comment by aloussase** [comment]
Thank you very much for getting in touch , it does indeed look promising. I'll give it a try later will look into that theme of yours as well!
